### ISSUE TITLE
editor cant export codeURL/art workURL

### ISSUE THREAD

**Issue by caoyuxistudio** [patriciogonzalezvivo/glslGallery#2]
Hey guys, try to figure it out this online nice glsl sets, but i got issue when i export the link in chrome or safari on pc or on mac, none of them show up the popup window of the shader link.  can you help check in that?

**Comment by patriciogonzalezvivo** [comment]
could you show us the error console?

**Comment by patriciogonzalezvivo** [comment]
the server went down... I restart it... should work now.
Thanks for the heads up
